export default class ChatGPTPlugin {
  constructor({ organization_id, secret_key, model, prompt, updatedVariable }) {
    this.organization_id = organization_id;
    this.secret_key = secret_key;
    this.model = model;
    this.prompt = prompt;
    this.updatedVariable = updatedVariable;
  }

  async init() {
    return {
    ROUTES: {
        GET: {
            "chat": (req, res) => this.chatHtml(req, res)
        },
        POST: {
            "chat-submit": (req, res) => this.chatSubmit(req, res)
        }
        },
      HOOKS: {
        "update": (stream) => this.query(stream),
        "add_metadata": (stream) => this.classify(stream),
      },
    };
  }

    /** Will query ChatGPT based on the plugin settings */ 
    async query(content) {
        // Parse the prompt string and replace placeholders with actual values
        const parsedPrompt = this.prompt.replace(/\$\{(\w+)\}/g, (_, variableName) => content[variableName]);
        console.log("parsedPrompt:", parsedPrompt);

        const result = await this.fetchFromOpenAI({
            "role": "user",
            "content": parsedPrompt
        });

        /** Will update the stream's content to add the description generated by GPT */
        let _content = {...content};
        _content[this.updatedVariable] = result;
        return _content
    }

    /** Will return a JSON object classifying the book */
    async classify(stream) {
        console.log("Enter classify with stream:", stream);
        console.log("will classify the the content in different categories.");
        const result = await this.fetchFromOpenAI({
            "role": "user",
            "content": "Can you return a JSON object classifying this book in mutiple categories while evaluating the target readers for this book? The json object should have two keys: categories (array of string) and readers (array of string):" + stream.content.Title + " by " + stream.content.Author
        }, "json_object");

        /** Will return the classification of the book  */
        return result;
    }

    chatHtml(req, res) {
        const { plugin_id, context_id } = req.params;
        res.send(`
          <html>
            <head>
                <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
                <style>
                    .chat-body {
                        background: #f1f5f9;
                    }
        
                    .chat-history {
                        height: 80%;
                        overflow: auto;
                        margin: 0;
                    }
        
                    .chat-input {
                        padding: 10px;
                        background-color: #f8fafc;
                        border-radius: 4px;
                    }
        
                    .chat-submit {
                        padding: 10px;
                        border: none;
                        background: #007BFF;
                        color: #fff;
                        border-radius: 4px;
                    }
        
                    .chat-loading {
                        display: block;
                        font-style: italic;
                        color: #888;
                    }
                </style>
            </head>
            <body class="chat-body bg-slate-100 text-sm w-full h-full flex flex-col">
              <div id="chat-history" class="p-6 chat-history overflow-y-scroll flex flex-1 flex-col w-full border-b border-slate-200"></div>
              <form class="chat-form bg-white p-4 flex flex-col mb-0">
                <textarea id="content" name="content" class="border border-slate-200 chat-input w-full bg-slate-50 mb-2" placeholder="Type your question here..."></textarea>
                <input type="submit" value="Submit" class="chat-submit w-full cursor-pointer">
              </form>
              <script>
                document.getElementById('chat-form').addEventListener('submit', function(event) {
                  event.preventDefault();
                  var content = document.getElementById('content').value;
                  document.getElementById('chat-history').innerHTML += '<p class="chat-message"><strong>You:</strong> ' + content + '</p>';
                  document.getElementById('chat-history').innerHTML += '<p id="loading" class="chat-loading"><strong>Bot:</strong> Is typing...</p>';
                  fetch('./chat-submit', {
                    method: 'POST',
                    headers: {
                      'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ content: content })
                  })
                  .then(response => response.json())
                  .then(result => {
                    console.log("Data:", result.data);
                    document.getElementById('loading').style.display = 'none';
                    document.getElementById('chat-history').innerHTML += '<p class="chat-message"><strong>Bot:</strong> ' + result.data + '</p>';
                  });
                });
              </script>
            </body>
          </html>
        `);
    }

    async chatSubmit(req, res) {
        if(req.body) {
            const { content } = req.body;
            console.log("Question asked:", content);
            const result = await this.fetchFromOpenAI({
                "role": "user",
                "content": content
            });
            console.log("Answer:", result);

            res.send({ data: result });
        } else {
            res.send({ data: null});
        }
    }

    /** Helper function to easily submit question to the OpenAI API */
    async fetchFromOpenAI(userMessage, response_format = "text" ) {
        const messages = [
            {
              "role": "system",
              "content": "You are a helpful assistant."
            },
            userMessage
        ];

        const response = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            "Content-Type": "application/json",
            'Authorization': `Bearer ${this.secret_key}`,
            'OpenAI-Organization': this.organization_id
          },
          body: JSON.stringify({
            model: "gpt-3.5-turbo-1106",
            response_format: { "type": response_format },
            messages: messages
          })
        });
    
        if (!response.ok) {
          console.error("Error with ChatGPTPlugin  " + response.statusText + ": ", response.status);
          return;
        }
    
        const data = await response.json();
        console.log("AI response: ", data.choices[0].message.content);
        return data.choices[0].message.content;
      }
}